milestone:
	pdflatex milestone.tex && \
	mv milestone.pdf CastroLindauer-AuthorIdentificationOnTwitter.pdf

finalreport: finalreport.tex
	pdflatex finalreport.tex && \
	mv finalreport.pdf CastroLindauer-AuthorIdentificationOnTwitter.pdf

macview: finalreport
	open CastroLindauer-AuthorIdentificationOnTwitter.pdf
